user  nginx;
worker_processes auto;

events {
    worker_connections 4096;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;

    client_max_body_size 25M;

    # -----------------------------
    # Compression (EDGE)
    # -----------------------------
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 5;
    gzip_min_length 1024;
    gzip_types
        text/plain text/css text/xml application/xml application/json application/javascript
        application/rss+xml application/atom+xml image/svg+xml;

    # ------------------------------------------------------------
    # Default catch-all: drop junk traffic fast
    # ------------------------------------------------------------
    server {
        listen 80 default_server;
        server_name _;
        return 444;
    }

    server {
        listen 443 ssl default_server;
        http2 on;
        server_name _;
        ssl_certificate     /etc/letsencrypt/live/bot.safecareorganisation.org/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/bot.safecareorganisation.org/privkey.pem;
        return 444;
    }

    # ================================
    #  BOT — HTTP (80) Redirect
    # ================================
    server {
        listen 80;
        server_name bot.safecareorganisation.org;

        location ^~ /storage/ {
            proxy_pass https://media.safecareorganisation.org;
            proxy_ssl_server_name on;
            proxy_set_header Host media.safecareorganisation.org;
        }

        location / {
            return 301 https://bot.safecareorganisation.org$request_uri;
        }
    }

    # =====================================
    #  BOT — HTTPS (443)
    # =====================================
    server {
        listen 443 ssl;
        http2 on;
        server_name bot.safecareorganisation.org;

        ssl_certificate     /etc/letsencrypt/live/bot.safecareorganisation.org/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/bot.safecareorganisation.org/privkey.pem;

        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-Content-Type-Options "nosniff";

        location ^~ /storage/ {
            proxy_pass https://safecareorganisation.org;
            proxy_ssl_server_name on;
            proxy_set_header Host safecareorganisation.org;
        }

        location / {
            proxy_pass http://cloud-bot:3001;
            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header Connection "";
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_connect_timeout 10s;
            proxy_send_timeout 60s;
            proxy_read_timeout 60s;
        }
    }
 }
